[project]
name = "sp-usd-creator"
version = "1.4.0"
requires-python = "==3.9.*"
dependencies = [
  "usd-core==24.5",
]

[dependency-groups]
dev = [
  "OpenImageIO",
  "pytest-cov",
  "pytest",
  "ruff",
]

[tool.ruff.lint.per-file-ignores]
"tests/test_usd_*.py" = ["E402"]
