[project]
name = "sp-usd-creator"
version = "0.0.0"
requires-python = ">=3.9"
dependencies = [
  "usd-core",
]

[dependency-groups]
dev = [
  "pytest-cov",
  "pytest",
  "ruff",
]

[tool.ruff.lint.per-file-ignores]
"tests/test_usd_*.py" = ["E402"]
